---
resources:
- name: repo
  type: git
  source:
    uri: git@github.com:making/simple-server-boshrelease.git
    branch: master
    private_key: {{github-private-key}}
- name: repo-version
  type: semver
  source:
    uri: git@github.com:making/simple-server-boshrelease.git
    branch: version
    private_key: {{github-private-key}}
    file: version
    driver: git
- name: ruby-release
  type: git
  source:
    uri: git@github.com:bosh-packages/ruby-release.git
    branch: master
    private_key: {{github-private-key}}
- name: gh-release
  type: github-release
  source:
    user: making
    repository: simple-server-boshrelease
    access_token: {{github-access-token}}

jobs:
- name: bosh-deploy-dev-in-docker
  plan:
  - aggregate:
    - get: repo
      trigger: true
    - get: ruby-release
      trigger: true
  - task: bosh-create-release
    config:
      <<: *BOSH_CREATE_RELEASE
  - task: bosh-deploy
    privileged: true
    params:
      RELEASE_NAME: simple-server
      IS_DOCKER: true
    config:
      <<: *BOSH_DEPLOY
- name: bosh-deploy-dev-in-exsiting-env
  plan:
  - aggregate:
    - get: repo
      trigger: true
    - get: ruby-release
      trigger: true
  - task: bosh-create-release
    config:
      <<: *BOSH_CREATE_RELEASE
  - task: bosh-deploy
    params:
      RELEASE_NAME: simple-server
      IS_DOCKER: false
      <<: *BOSH
    config:
      <<: *BOSH_DEPLOY
- name: ship-it
  plan:
  - aggregate:
    - get: repo
      passed:
      - bosh-deploy-dev-in-exsiting-env
      - bosh-deploy-dev-in-docker
    - get: repo-version
    - get: ruby-release
  - task: create-release
    params:
      <<: *BOSH
      GIT_EMAIL: {{git-email}}
      GIT_NAME: {{git-name}}
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: bosh/main-bosh-docker
      inputs:
      - name: repo
      - name: repo-version
      - name: ruby-release
      outputs:
      - name: releases
      - name: updated-repo
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd repo
          shopt -s dotglob
          cp -r ./* ../updated-repo
          rm -rf .final_builds releases
          VERSION=`cat ../repo-version/number`
          TARBALL=simple-server-boshrelease-${VERSION}.tgz

          bosh vendor-package ruby-2.4 ../ruby-release
          bosh create-release --force --version=${VERSION} --final --tarball=../releases/${TARBALL}
          
          SHA1=`sha1sum ../releases/${TARBALL} | awk '{print $1}'`
          mkdir -p .sha1
          echo ${SHA1} > .sha1/${VERSION}
          
          cp -r ./* ../updated-repo
          cd ../updated-repo
          git config --global user.email "${GIT_EMAIL}"
          git config --global user.name "${GIT_NAME}"
          git add -A
          git commit -m "Release ${VERSION}"

          # Release Note
          cat <<EOF > ../releases/note.md
          ## Deployment

          \`\`\` yaml
          # manifest.yml
          ---
          name: simple-server
          releases:
          - name: simple-server
            version: ${VERSION}
            url: https://github.com/making/simple-server-boshrelease/releases/download/${VERSION}/${TARBALL}
            sha1: ${SHA1}

          stemcells:
          - alias: trusty
            os: ubuntu-trusty
            version: latest

          instance_groups:
          - name: app
            jobs:
            - name: app
              release: simple-server
              properties:
                port: 8080
            instances: 2
            stemcell: trusty
            azs: [z1]
            vm_type: default
            networks:
            - name: default

          - name: router
            jobs:
            - name: router
              release: simple-server
              properties:
                port: 8080
            instances: 1
            stemcell: trusty
            azs: [z1]
            vm_type: default
            networks:
            - name: default
              static_ips: ((router-ip))

          update:
            canaries: 1
            max_in_flight: 1
            serial: false
            canary_watch_time: 1000-60000
            update_watch_time: 1000-60000
          \`\`\`

          To deploy:

          \`\`\`
          bosh deploy -d simple-server manifest.yml -v router-ip=10.244.0.235
          \`\`\`
          EOF
  - put: repo
    params:
      repository: updated-repo
      tag: repo-version/number
  - put: gh-release
    params:
      name: repo-version/number
      tag: repo-version/number
      body: releases/note.md
      globs:
      - releases/*.tgz

########################################

- name: bump-to-next-patch-version
  plan:
  - aggregate:
    - get: repo
      trigger: true
      passed:
      - ship-it
    - get: repo-version
      params:
        bump: patch
  - put: repo-version
    params:
      file: repo-version/number

- name: bump-to-next-minor-version
  plan:
  - aggregate:
    - get: repo-version
      params:
        bump: minor
  - put: repo-version
    params:
      file: repo-version/number

- name: bump-to-next-majar-version
  plan:
  - aggregate:
    - get: repo-version
      params:
        bump: majar
  - put: repo-version
    params:
      file: repo-version/number

params:
  bosh: &BOSH
    BOSH_CLIENT: {{bosh-client}}
    BOSH_ENVIRONMENT: {{bosh-environment}}
    BOSH_CLIENT_SECRET: {{bosh-client-secret}}
    BOSH_CA_CERT: {{bosh-ca-cert}}
tasks:
  bosh-create-release: &BOSH_CREATE_RELEASE
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: bosh/main-bosh-docker
    inputs:
    - name: repo
    - name: ruby-release
    outputs:
    - name: releases
    run:
      path: bash
      args: 
      - -c
      - |
        set -e
        cd repo
        rm -rf .final_builds releases
        bosh vendor-package ruby-2.4 ../ruby-release
        bosh create-release --name=simple-server-dev --force --timestamp-version --tarball=../releases/simple-server-boshrelease.tgz
  bosh-deploy: &BOSH_DEPLOY
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: bosh/main-bosh-docker
    inputs:
    - name: repo
    - name: releases
    run:
      path: bash
      args: 
      - -c
      - |
        set -e

        if [ "${IS_DOCKER}" == "true" ];then
          start-bosh
          source /tmp/local-bosh/director/env
          bosh upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent?v=3445.11
        fi

        bosh env
        bosh upload-release releases/*.tgz
        cd repo
        cat <<EOF > ops.yml
        - type: remove
          path: /instance_groups/name=router/networks/name=default/static_ips
        EOF
        sed -i "s/${RELEASE_NAME}/${RELEASE_NAME}-dev/" manifest.yml
        bosh -n deploy -d ${RELEASE_NAME}-dev <(bosh int manifest.yml -o ops.yml)
        bosh vms -d ${RELEASE_NAME}-dev

        router_ip=`bosh vms -d ${RELEASE_NAME}-dev | grep router | awk '{print $4}'`
        
        echo "Running Smoke Test... to ${router_ip}"
        for i in `seq 1 50`;do
          status_code=`curl -L http://${router_ip}:8080 -o /dev/null -w '%{http_code}\n' -s`
          if [ "${status_code}" != "200" ];then
            echo "Test Failed: Got ${status_code}"
            exit 1
          fi
        done
        echo "Test Passed"

        bosh -n delete-deployment -d ${RELEASE_NAME}-dev